---
services:
  postgres:
    image: postgres:17.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: budgie_user
      POSTGRES_DB: budgie_db
      POSTGRES_PASSWORD: budgie_pazzwerdz
    container_name: budgie
